export interface Sticker {
  name: string;
  wear?: number; // 0-100 for sticker wear
  position: number; // 1-4 for position on weapon
}

export interface Charm {
  name: string;
}

export interface MarketLinks {
  lisSkins?: string;
  steamMarket?: string;
  marketCSGO?: string;
}

export interface TradingItem {
  id: string;
  itemName: string;
  buyPrice: number;
  buyDate: string;
  market: "Lis-Skins" | "Market.CSGO" | "Steam Market";
  assetId: string;
  status: "sold" | "unsold" | "waiting_unlock" | "trade_ban";
  sellPrice: number | null;
  sellDate: string | null;
  sellMarket?: "Lis-Skins" | "Market.CSGO" | "Steam Market" | null;
  targetSellMarket?: "Lis-Skins" | "Market.CSGO" | "Steam Market" | null; // Selected marketplace during import
  currentMarketPrice?: number; // Current lowest price on target marketplace
  unlock_at?: string | null; // ISO date string when item becomes tradable
  trade_ban_until?: string | null; // ISO date string when trade ban expires
  delivered_to_steam?: boolean; // Whether item has been delivered to Steam inventory
  profit: number;
  profitPercentage: number;
  potentialProfit: number;
  tags: string[];
  stickers: Sticker[];
  charm?: Charm;
  marketLinks: MarketLinks;
  accountId: string; // Steam account this item belongs to
}

export interface TradingStats {
  totalSpent: number;
  totalEarned: number;
  totalProfit: number;
  averageROI: number;
  itemsInInventory: number;
  totalItems: number;
}

export interface SteamAccountBasic {
  id: string;
  nickname: string;
}

// Steam accounts for dropdown selector
export const mockSteamAccountsBasic: SteamAccountBasic[] = [
  { id: "all", nickname: "All Accounts" },
  { id: "1", nickname: "Trader 1" },
  { id: "2", nickname: "Trader 2" },
  { id: "3", nickname: "Bot Account 1" },
  { id: "4", nickname: "Storage Bot" },
  { id: "5", nickname: "Trader 3" },
  { id: "6", nickname: "Market Bot" },
];

// Mock data with 50 diverse test items
export const mockTradingItems: TradingItem[] = [
  {
    id: "1",
    itemName: "AK-47 | Redline (Field-Tested)",
    buyPrice: 85.5,
    buyDate: "2023-10-15",
    market: "Lis-Skins",
    assetId: "LS_789123456",
    status: "sold",
    sellPrice: 92.3,
    sellDate: "2023-10-22",
    sellMarket: "Steam Market",
    profit: 6.8,
    profitPercentage: 7.95,
    potentialProfit: 0,
    tags: ["flip", "ak47"],
    stickers: [
      { name: "Howling Dawn", wear: 10, position: 1 },
      { name: "iBUYPOWER | Katowice 2014", wear: 25, position: 2 },
    ],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/ak47-redline-ft",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Redline%20%28Field-Tested%29",
      marketCSGO: "https://market.csgo.com/item/ak47-redline-ft",
    },
    accountId: "1",
  },
  {
    id: "2",
    itemName: "AWP | Dragon Lore (Well-Worn)",
    buyPrice: 4250.0,
    buyDate: "2023-11-10",
    market: "Market.CSGO",
    assetId: "MC_456789123",
    status: "sold",
    sellPrice: 4680.0,
    sellDate: "2023-12-15",
    sellMarket: "Lis-Skins",
    profit: 430.0,
    profitPercentage: 10.12,
    potentialProfit: 0,
    tags: ["invest", "awp", "high-tier"],
    stickers: [],
    charm: { name: "Gold Web Stuck" },
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/awp-dragon-lore-ww",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/AWP%20%7C%20Dragon%20Lore%20%28Well-Worn%29",
      marketCSGO: "https://market.csgo.com/item/awp-dragon-lore-ww",
    },
    accountId: "2",
  },
  {
    id: "3",
    itemName: "M4A4 | Howl (Minimal Wear)",
    buyPrice: 2850.75,
    buyDate: "2023-11-08",
    market: "Steam Market",
    assetId: "SM_123789456",
    status: "sold",
    sellPrice: 3120.5,
    sellDate: "2023-12-25",
    sellMarket: "Lis-Skins",
    profit: 269.75,
    profitPercentage: 9.46,
    potentialProfit: 0,
    tags: ["invest", "m4a4", "contraband"],
    stickers: [
      { name: "Reason Gaming | Katowice 2014", wear: 5, position: 1 },
      { name: "Team Dignitas | Katowice 2014", wear: 8, position: 2 },
      { name: "Clan-Mystik | Katowice 2014", wear: 12, position: 3 },
    ],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/m4a4-howl-mw",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/M4A4%20%7C%20Howl%20%28Minimal%20Wear%29",
      marketCSGO: "https://market.csgo.com/item/m4a4-howl-mw",
    },
    accountId: "1",
  },
  {
    id: "4",
    itemName: "Glock-18 | Fade (Factory New)",
    buyPrice: 340.2,
    buyDate: "2023-12-20",
    market: "Steam Market",
    assetId: "SM_987654321",
    status: "ready_to_trade",
    sellPrice: null,
    sellDate: null,
    targetSellMarket: "Market.CSGO",
    currentMarketPrice: 355.5,
    delivered_to_steam: true,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 15.3,
    tags: ["hold", "glock"],
    stickers: [{ name: "Crown (Foil)", wear: 0, position: 1 }],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/glock-18-fade-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/Glock-18%20%7C%20Fade%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/glock-18-fade-fn",
    },
    accountId: "3",
  },
  {
    id: "5",
    itemName: "Karambit | Crimson Web (Minimal Wear)",
    buyPrice: 1850.0,
    buyDate: "2023-11-12",
    market: "Lis-Skins",
    assetId: "LS_555123789",
    status: "sold",
    sellPrice: 1920.5,
    sellDate: "2024-01-28",
    sellMarket: "Market.CSGO",
    profit: 70.5,
    profitPercentage: 3.81,
    potentialProfit: 0,
    tags: ["flip", "knife", "karambit"],
    stickers: [],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/karambit-crimson-web-mw",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/Karambit%20%7C%20Crimson%20Web%20%28Minimal%20Wear%29",
      marketCSGO: "https://market.csgo.com/item/karambit-crimson-web-mw",
    },
    accountId: "1",
  },
  {
    id: "6",
    itemName: "AK-47 | Fire Serpent (Field-Tested)",
    buyPrice: 680.3,
    buyDate: "2024-01-18",
    market: "Market.CSGO",
    assetId: "MC_111222333",
    status: "trade_ban",
    sellPrice: null,
    sellDate: null,
    targetSellMarket: "Lis-Skins",
    currentMarketPrice: 715.9,
    delivered_to_steam: true,
    trade_ban_until: "2024-02-15T10:30:00Z",
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 35.6,
    tags: ["hold", "ak47"],
    stickers: [
      { name: "Titan | Katowice 2014", wear: 15, position: 1 },
      { name: "Natus Vincere | Katowice 2014", wear: 20, position: 2 },
      { name: "Virtus.pro | Katowice 2014", wear: 18, position: 3 },
      { name: "LGB eSports | Katowice 2014", wear: 22, position: 4 },
    ],
    charm: { name: "Terrorist Fist Bump" },
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/ak47-fire-serpent-ft",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Fire%20Serpent%20%28Field-Tested%29",
      marketCSGO: "https://market.csgo.com/item/ak47-fire-serpent-ft",
    },
    accountId: "2",
  },
  {
    id: "7",
    itemName: "StatTrak™ M4A1-S | Hyper Beast (Field-Tested)",
    buyPrice: 125.75,
    buyDate: "2023-12-25",
    market: "Steam Market",
    assetId: "SM_789456123",
    status: "sold",
    sellPrice: 142.3,
    sellDate: "2024-02-02",
    sellMarket: "Market.CSGO",
    profit: 16.55,
    profitPercentage: 13.16,
    potentialProfit: 0,
    tags: ["stattrak", "m4a1s"],
    stickers: [
      { name: "Team Liquid | MLG Columbus 2016", wear: 35, position: 1 },
      { name: "FaZe Clan | MLG Columbus 2016", wear: 40, position: 2 },
    ],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/m4a1s-hyper-beast-ft-st",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/StatTrak%E2%84%A2%20M4A1-S%20%7C%20Hyper%20Beast%20%28Field-Tested%29",
      marketCSGO: "https://market.csgo.com/item/m4a1s-hyper-beast-ft-st",
    },
    accountId: "3",
  },
  {
    id: "8",
    itemName: "★ Butterfly Knife | Doppler (Factory New)",
    buyPrice: 1245.0,
    buyDate: "2024-02-01",
    market: "Lis-Skins",
    assetId: "LS_999888777",
    status: "unsold",
    sellPrice: null,
    sellDate: null,
    targetSellMarket: "Steam Market",
    currentMarketPrice: 1180.5,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: -64.5,
    tags: ["knife", "butterfly", "doppler"],
    stickers: [],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/butterfly-knife-doppler-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/%E2%98%85%20Butterfly%20Knife%20%7C%20Doppler%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/butterfly-knife-doppler-fn",
    },
    accountId: "4",
  },
  {
    id: "9",
    itemName: "USP-S | Kill Confirmed (Minimal Wear)",
    buyPrice: 45.2,
    buyDate: "2024-01-30",
    market: "Market.CSGO",
    assetId: "MC_555666777",
    status: "unsold",
    sellPrice: null,
    sellDate: null,
    targetSellMarket: "Lis-Skins",
    currentMarketPrice: 52.75,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 7.55,
    tags: ["usps", "pistol"],
    stickers: [{ name: "Skull Troop", wear: 15, position: 1 }],
    charm: { name: "Death Awaits" },
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/usps-kill-confirmed-mw",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/USP-S%20%7C%20Kill%20Confirmed%20%28Minimal%20Wear%29",
      marketCSGO: "https://market.csgo.com/item/usps-kill-confirmed-mw",
    },
    accountId: "5",
  },
  {
    id: "10",
    itemName: "★ Karambit | Fade (Factory New)",
    buyPrice: 2890.0,
    buyDate: "2023-10-05",
    market: "Steam Market",
    assetId: "SM_111333555",
    status: "sold",
    sellPrice: 3125.75,
    sellDate: "2023-11-18",
    sellMarket: "Lis-Skins",
    profit: 235.75,
    profitPercentage: 8.16,
    potentialProfit: 0,
    tags: ["knife", "karambit", "fade"],
    stickers: [],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/karambit-fade-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/%E2%98%85%20Karambit%20%7C%20Fade%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/karambit-fade-fn",
    },
    accountId: "1",
  },
  {
    id: "11",
    itemName: "Desert Eagle | Blaze (Factory New)",
    buyPrice: 185.3,
    buyDate: "2024-02-05",
    market: "Market.CSGO",
    assetId: "MC_777888999",
    status: "unsold",
    sellPrice: null,
    sellDate: null,
    targetSellMarket: "Steam Market",
    currentMarketPrice: 195.8,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 10.5,
    tags: ["deagle", "pistol"],
    stickers: [
      { name: "Flammable (Foil)", wear: 5, position: 1 },
      { name: "Phoenix (Foil)", wear: 8, position: 2 },
    ],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/deagle-blaze-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/Desert%20Eagle%20%7C%20Blaze%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/deagle-blaze-fn",
    },
    accountId: "6",
  },
  {
    id: "12",
    itemName: "AK-47 | Case Hardened (Battle-Scarred)",
    buyPrice: 95.75,
    buyDate: "2023-12-28",
    market: "Lis-Skins",
    assetId: "LS_444555666",
    status: "sold",
    sellPrice: 87.2,
    sellDate: "2024-02-08",
    sellMarket: "Market.CSGO",
    profit: -8.55,
    profitPercentage: -8.93,
    potentialProfit: 0,
    tags: ["ak47", "case-hardened"],
    stickers: [
      { name: "Blue Gem", wear: 25, position: 1 },
      { name: "Golden Coil", wear: 30, position: 2 },
    ],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/ak47-case-hardened-bs",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Case%20Hardened%20%28Battle-Scarred%29",
      marketCSGO: "https://market.csgo.com/item/ak47-case-hardened-bs",
    },
    accountId: "2",
  },
  {
    id: "13",
    itemName: "StatTrak™ AWP | Asiimov (Field-Tested)",
    buyPrice: 485.9,
    buyDate: "2024-02-03",
    market: "Steam Market",
    assetId: "SM_123123123",
    status: "unsold",
    sellPrice: null,
    sellDate: null,
    targetSellMarket: "Market.CSGO",
    currentMarketPrice: 505.25,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 19.35,
    tags: ["stattrak", "awp", "asiimov"],
    stickers: [
      { name: "kennyS | Cluj-Napoca 2015", wear: 10, position: 1 },
      { name: "GuardiaN | Cluj-Napoca 2015", wear: 12, position: 2 },
    ],
    charm: { name: "Sniper's Focus" },
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/awp-asiimov-ft-st",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/StatTrak%E2%84%A2%20AWP%20%7C%20Asiimov%20%28Field-Tested%29",
      marketCSGO: "https://market.csgo.com/item/awp-asiimov-ft-st",
    },
    accountId: "3",
  },
  {
    id: "14",
    itemName: "★ Bayonet | Tiger Tooth (Factory New)",
    buyPrice: 755.4,
    buyDate: "2023-11-22",
    market: "Market.CSGO",
    assetId: "MC_987987987",
    status: "sold",
    sellPrice: 812.85,
    sellDate: "2024-01-01",
    sellMarket: "Steam Market",
    profit: 57.45,
    profitPercentage: 7.61,
    potentialProfit: 0,
    tags: ["knife", "bayonet", "tiger-tooth"],
    stickers: [],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/bayonet-tiger-tooth-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/%E2%98%85%20Bayonet%20%7C%20Tiger%20Tooth%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/bayonet-tiger-tooth-fn",
    },
    accountId: "4",
  },
  {
    id: "15",
    itemName: "M4A4 | Neo-Noir (Field-Tested)",
    buyPrice: 78.65,
    buyDate: "2024-02-06",
    market: "Lis-Skins",
    assetId: "LS_666777888",
    status: "unsold",
    sellPrice: null,
    sellDate: null,
    targetSellMarket: "Steam Market",
    currentMarketPrice: 82.4,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 3.75,
    tags: ["m4a4", "neo-noir"],
    stickers: [{ name: "Virtus.pro | Boston 2018", wear: 20, position: 1 }],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/m4a4-neo-noir-ft",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/M4A4%20%7C%20Neo-Noir%20%28Field-Tested%29",
      marketCSGO: "https://market.csgo.com/item/m4a4-neo-noir-ft",
    },
    accountId: "5",
  },
  {
    id: "16",
    itemName: "AWP | Medusa (Well-Worn)",
    buyPrice: 2150.0,
    buyDate: "2023-10-08",
    market: "Steam Market",
    assetId: "SM_456456456",
    status: "sold",
    sellPrice: 2380.75,
    sellDate: "2023-12-10",
    sellMarket: "Lis-Skins",
    profit: 230.75,
    profitPercentage: 10.73,
    potentialProfit: 0,
    tags: ["awp", "medusa", "contraband"],
    stickers: [],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/awp-medusa-ww",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/AWP%20%7C%20Medusa%20%28Well-Worn%29",
      marketCSGO: "https://market.csgo.com/item/awp-medusa-ww",
    },
    accountId: "1",
  },
  {
    id: "17",
    itemName: "Galil AR | Cerberus (Minimal Wear)",
    buyPrice: 28.4,
    buyDate: "2024-02-04",
    market: "Market.CSGO",
    assetId: "MC_321321321",
    status: "sold",
    sellPrice: 31.95,
    sellDate: "2024-02-09",
    sellMarket: "Lis-Skins",
    profit: 3.55,
    profitPercentage: 12.5,
    potentialProfit: 0,
    tags: ["galil", "rifle"],
    stickers: [{ name: "Cerberus", wear: 18, position: 1 }],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/galil-cerberus-mw",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/Galil%20AR%20%7C%20Cerberus%20%28Minimal%20Wear%29",
      marketCSGO: "https://market.csgo.com/item/galil-cerberus-mw",
    },
    accountId: "1",
  },
  {
    id: "18",
    itemName: "P250 | Nuclear Threat (Minimal Wear)",
    buyPrice: 155.75,
    buyDate: "2024-01-26",
    market: "Lis-Skins",
    assetId: "LS_159159159",
    status: "unsold",
    sellPrice: null,
    sellDate: null,
    targetSellMarket: "Market.CSGO",
    currentMarketPrice: 168.9,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 13.15,
    tags: ["p250", "pistol"],
    stickers: [
      { name: "Radioactive", wear: 22, position: 1 },
      { name: "Biohazard", wear: 25, position: 2 },
    ],
    charm: { name: "Toxic Waste" },
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/p250-nuclear-threat-mw",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/P250%20%7C%20Nuclear%20Threat%20%28Minimal%20Wear%29",
      marketCSGO: "https://market.csgo.com/item/p250-nuclear-threat-mw",
    },
    accountId: "2",
  },
  {
    id: "19",
    itemName: "AK-47 | Vulcan (Field-Tested)",
    buyPrice: 285.5,
    buyDate: "2024-02-09",
    market: "Steam Market",
    assetId: "SM_777999111",
    status: "waiting_unlock",
    sellPrice: null,
    sellDate: null,
    unlock_at: "2024-02-16T14:30:00Z",
    delivered_to_steam: false,
    targetSellMarket: "Market.CSGO",
    currentMarketPrice: 295.75,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 10.25,
    tags: ["ak47", "vulcan"],
    stickers: [{ name: "Team EnVyUs | Katowice 2015", wear: 15, position: 1 }],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/ak47-vulcan-ft",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Vulcan%20%28Field-Tested%29",
      marketCSGO: "https://market.csgo.com/item/ak47-vulcan-ft",
    },
    accountId: "3",
  },
  {
    id: "20",
    itemName: "★ M9 Bayonet | Marble Fade (Factory New)",
    buyPrice: 1845.0,
    buyDate: "2024-02-10",
    market: "Lis-Skins",
    assetId: "LS_888111222",
    status: "waiting_unlock",
    sellPrice: null,
    sellDate: null,
    unlock_at: "2024-02-17T10:15:00Z",
    targetSellMarket: "Steam Market",
    currentMarketPrice: 1920.5,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 75.5,
    tags: ["knife", "m9", "marble-fade"],
    stickers: [],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/m9-bayonet-marble-fade-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/%E2%98%85%20M9%20Bayonet%20%7C%20Marble%20Fade%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/m9-bayonet-marble-fade-fn",
    },
    accountId: "4",
  },
  {
    id: "21",
    itemName: "★ Huntsman Knife | Slaughter (Factory New)",
    buyPrice: 890.0,
    buyDate: "2023-09-15",
    market: "Market.CSGO",
    assetId: "MC_555444333",
    status: "sold",
    sellPrice: 965.75,
    sellDate: "2023-11-25",
    sellMarket: "Steam Market",
    profit: 75.75,
    profitPercentage: 8.51,
    potentialProfit: 0,
    tags: ["knife", "huntsman", "slaughter"],
    stickers: [],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/huntsman-slaughter-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/%E2%98%85%20Huntsman%20Knife%20%7C%20Slaughter%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/huntsman-slaughter-fn",
    },
    accountId: "2",
  },
  {
    id: "22",
    itemName: "M4A1-S | Knight (Factory New)",
    buyPrice: 1250.0,
    buyDate: "2023-10-20",
    market: "Steam Market",
    assetId: "SM_222333444",
    status: "sold",
    sellPrice: 1385.5,
    sellDate: "2024-01-15",
    sellMarket: "Market.CSGO",
    profit: 135.5,
    profitPercentage: 10.84,
    potentialProfit: 0,
    tags: ["m4a1s", "knight", "contraband"],
    stickers: [{ name: "Crown (Foil)", wear: 0, position: 1 }],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/m4a1s-knight-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/M4A1-S%20%7C%20Knight%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/m4a1s-knight-fn",
    },
    accountId: "5",
  },
  {
    id: "23",
    itemName: "AWP | Lightning Strike (Factory New)",
    buyPrice: 195.25,
    buyDate: "2023-11-30",
    market: "Lis-Skins",
    assetId: "LS_666555444",
    status: "sold",
    sellPrice: 218.4,
    sellDate: "2024-01-08",
    sellMarket: "Steam Market",
    profit: 23.15,
    profitPercentage: 11.86,
    potentialProfit: 0,
    tags: ["awp", "lightning"],
    stickers: [
      { name: "Fnatic | Katowice 2014", wear: 12, position: 1 },
      { name: "mousesports | Katowice 2014", wear: 15, position: 2 },
    ],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/awp-lightning-strike-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/AWP%20%7C%20Lightning%20Strike%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/awp-lightning-strike-fn",
    },
    accountId: "6",
  },
  {
    id: "24",
    itemName: "★ Flip Knife | Doppler (Factory New)",
    buyPrice: 585.0,
    buyDate: "2024-01-12",
    market: "Market.CSGO",
    assetId: "MC_777666555",
    status: "unsold",
    sellPrice: null,
    sellDate: null,
    targetSellMarket: "Lis-Skins",
    currentMarketPrice: 598.75,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 13.75,
    tags: ["knife", "flip", "doppler"],
    stickers: [],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/flip-knife-doppler-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/%E2%98%85%20Flip%20Knife%20%7C%20Doppler%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/flip-knife-doppler-fn",
    },
    accountId: "1",
  },
  {
    id: "25",
    itemName: "Five-SeveN | Case Hardened (Minimal Wear)",
    buyPrice: 12.5,
    buyDate: "2024-01-20",
    market: "Steam Market",
    assetId: "SM_888777666",
    status: "sold",
    sellPrice: 18.75,
    sellDate: "2024-02-01",
    sellMarket: "Market.CSGO",
    profit: 6.25,
    profitPercentage: 50.0,
    potentialProfit: 0,
    tags: ["five-seven", "blue-gem"],
    stickers: [{ name: "ESL One Cologne 2014 (Blue)", wear: 20, position: 1 }],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/five-seven-case-hardened-mw",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/Five-SeveN%20%7C%20Case%20Hardened%20%28Minimal%20Wear%29",
      marketCSGO: "https://market.csgo.com/item/five-seven-case-hardened-mw",
    },
    accountId: "3",
  },
  {
    id: "26",
    itemName: "StatTrak™ AK-47 | Bloodsport (Minimal Wear)",
    buyPrice: 165.0,
    buyDate: "2023-12-05",
    market: "Lis-Skins",
    assetId: "LS_999888777",
    status: "unsold",
    sellPrice: null,
    sellDate: null,
    targetSellMarket: "Market.CSGO",
    currentMarketPrice: 178.5,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 13.5,
    tags: ["stattrak", "ak47", "bloodsport"],
    stickers: [
      { name: "Astralis | Boston 2018", wear: 25, position: 1 },
      { name: "FaZe Clan | Boston 2018", wear: 30, position: 2 },
    ],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/ak47-bloodsport-mw-st",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/StatTrak%E2%84%A2%20AK-47%20%7C%20Bloodsport%20%28Minimal%20Wear%29",
      marketCSGO: "https://market.csgo.com/item/ak47-bloodsport-mw-st",
    },
    accountId: "4",
  },
  {
    id: "27",
    itemName: "★ Skeleton Knife | Fade (Factory New)",
    buyPrice: 1385.0,
    buyDate: "2023-09-28",
    market: "Steam Market",
    assetId: "SM_111222999",
    status: "sold",
    sellPrice: 1520.75,
    sellDate: "2023-12-18",
    sellMarket: "Lis-Skins",
    profit: 135.75,
    profitPercentage: 9.8,
    potentialProfit: 0,
    tags: ["knife", "skeleton", "fade"],
    stickers: [],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/skeleton-knife-fade-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/%E2%98%85%20Skeleton%20Knife%20%7C%20Fade%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/skeleton-knife-fade-fn",
    },
    accountId: "2",
  },
  {
    id: "28",
    itemName: "M4A4 | Asiimov (Field-Tested)",
    buyPrice: 95.5,
    buyDate: "2024-01-15",
    market: "Market.CSGO",
    assetId: "MC_333444555",
    status: "trade_ban",
    sellPrice: null,
    sellDate: null,
    delivered_to_steam: true,
    trade_ban_until: "2024-02-18T09:00:00Z",
    targetSellMarket: "Steam Market",
    currentMarketPrice: 102.25,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 6.75,
    tags: ["m4a4", "asiimov"],
    stickers: [{ name: "Neon Revolution", wear: 40, position: 1 }],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/m4a4-asiimov-ft",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/M4A4%20%7C%20Asiimov%20%28Field-Tested%29",
      marketCSGO: "https://market.csgo.com/item/m4a4-asiimov-ft",
    },
    accountId: "5",
  },
  {
    id: "29",
    itemName: "Tec-9 | Nuclear Threat (Minimal Wear)",
    buyPrice: 68.25,
    buyDate: "2023-11-18",
    market: "Lis-Skins",
    assetId: "LS_444333222",
    status: "sold",
    sellPrice: 79.9,
    sellDate: "2024-01-22",
    sellMarket: "Market.CSGO",
    profit: 11.65,
    profitPercentage: 17.07,
    potentialProfit: 0,
    tags: ["tec9", "nuclear"],
    stickers: [
      { name: "Bomb Doge", wear: 35, position: 1 },
      { name: "Rekt (Holo)", wear: 20, position: 2 },
    ],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/tec9-nuclear-threat-mw",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/Tec-9%20%7C%20Nuclear%20Threat%20%28Minimal%20Wear%29",
      marketCSGO: "https://market.csgo.com/item/tec9-nuclear-threat-mw",
    },
    accountId: "6",
  },
  {
    id: "30",
    itemName: "★ Talon Knife | Tiger Tooth (Factory New)",
    buyPrice: 1125.0,
    buyDate: "2024-01-05",
    market: "Steam Market",
    assetId: "SM_555444777",
    status: "ready_to_trade",
    sellPrice: null,
    sellDate: null,
    delivered_to_steam: true,
    targetSellMarket: "Lis-Skins",
    currentMarketPrice: 1165.5,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 40.5,
    tags: ["knife", "talon", "tiger-tooth"],
    stickers: [],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/talon-knife-tiger-tooth-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Tiger%20Tooth%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/talon-knife-tiger-tooth-fn",
    },
    accountId: "1",
  },
  {
    id: "31",
    itemName: "CZ75-Auto | Emerald (Factory New)",
    buyPrice: 125.0,
    buyDate: "2023-10-25",
    market: "Market.CSGO",
    assetId: "MC_666555888",
    status: "sold",
    sellPrice: 95.75,
    sellDate: "2023-12-28",
    sellMarket: "Steam Market",
    profit: -29.25,
    profitPercentage: -23.4,
    potentialProfit: 0,
    tags: ["cz75", "emerald"],
    stickers: [{ name: "Emerald Pinstripe", wear: 10, position: 1 }],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/cz75-auto-emerald-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/CZ75-Auto%20%7C%20Emerald%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/cz75-auto-emerald-fn",
    },
    accountId: "3",
  },
  {
    id: "32",
    itemName: "AWP | Containment Breach (Field-Tested)",
    buyPrice: 58.5,
    buyDate: "2024-01-28",
    market: "Lis-Skins",
    assetId: "LS_777888999",
    status: "unsold",
    sellPrice: null,
    sellDate: null,
    targetSellMarket: "Market.CSGO",
    currentMarketPrice: 64.25,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 5.75,
    tags: ["awp", "containment"],
    stickers: [{ name: "Backstab", wear: 45, position: 1 }],
    charm: { name: "CT in Banana" },
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/awp-containment-breach-ft",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/AWP%20%7C%20Containment%20Breach%20%28Field-Tested%29",
      marketCSGO: "https://market.csgo.com/item/awp-containment-breach-ft",
    },
    accountId: "4",
  },
  {
    id: "33",
    itemName: "★ Gut Knife | Gamma Doppler (Factory New)",
    buyPrice: 425.0,
    buyDate: "2023-12-12",
    market: "Steam Market",
    assetId: "SM_888999111",
    status: "sold",
    sellPrice: 465.75,
    sellDate: "2024-02-05",
    sellMarket: "Market.CSGO",
    profit: 40.75,
    profitPercentage: 9.59,
    potentialProfit: 0,
    tags: ["knife", "gut", "gamma-doppler"],
    stickers: [],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/gut-knife-gamma-doppler-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/%E2%98%85%20Gut%20Knife%20%7C%20Gamma%20Doppler%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/gut-knife-gamma-doppler-fn",
    },
    accountId: "5",
  },
  {
    id: "34",
    itemName: "StatTrak™ USP-S | Orion (Factory New)",
    buyPrice: 185.0,
    buyDate: "2023-11-05",
    market: "Lis-Skins",
    assetId: "LS_222111333",
    status: "sold",
    sellPrice: 205.5,
    sellDate: "2024-01-10",
    sellMarket: "Steam Market",
    profit: 20.5,
    profitPercentage: 11.08,
    potentialProfit: 0,
    tags: ["stattrak", "usps", "orion"],
    stickers: [
      { name: "Cloud9 G2A | Katowice 2015", wear: 18, position: 1 },
      { name: "Team Liquid | Katowice 2015", wear: 22, position: 2 },
    ],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/usps-orion-fn-st",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/StatTrak%E2%84%A2%20USP-S%20%7C%20Orion%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/usps-orion-fn-st",
    },
    accountId: "6",
  },
  {
    id: "35",
    itemName: "AK-47 | Neon Rider (Field-Tested)",
    buyPrice: 95.0,
    buyDate: "2024-02-08",
    market: "Market.CSGO",
    assetId: "MC_333222444",
    status: "waiting_unlock",
    sellPrice: null,
    sellDate: null,
    unlock_at: "2024-02-15T16:20:00Z",
    delivered_to_steam: false,
    targetSellMarket: "Lis-Skins",
    currentMarketPrice: 102.75,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 7.75,
    tags: ["ak47", "neon-rider"],
    stickers: [{ name: "Neon Revolution", wear: 35, position: 1 }],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/ak47-neon-rider-ft",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Neon%20Rider%20%28Field-Tested%29",
      marketCSGO: "https://market.csgo.com/item/ak47-neon-rider-ft",
    },
    accountId: "1",
  },
  {
    id: "36",
    itemName: "★ Bowie Knife | Case Hardened (Minimal Wear)",
    buyPrice: 385.0,
    buyDate: "2023-09-18",
    market: "Steam Market",
    assetId: "SM_444555777",
    status: "sold",
    sellPrice: 428.25,
    sellDate: "2023-11-28",
    sellMarket: "Lis-Skins",
    profit: 43.25,
    profitPercentage: 11.23,
    potentialProfit: 0,
    tags: ["knife", "bowie", "case-hardened"],
    stickers: [],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/bowie-knife-case-hardened-mw",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/%E2%98%85%20Bowie%20Knife%20%7C%20Case%20Hardened%20%28Minimal%20Wear%29",
      marketCSGO: "https://market.csgo.com/item/bowie-knife-case-hardened-mw",
    },
    accountId: "2",
  },
  {
    id: "37",
    itemName: "M4A1-S | Decimator (Minimal Wear)",
    buyPrice: 42.75,
    buyDate: "2024-01-22",
    market: "Lis-Skins",
    assetId: "LS_555666888",
    status: "unsold",
    sellPrice: null,
    sellDate: null,
    targetSellMarket: "Steam Market",
    currentMarketPrice: 48.9,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 6.15,
    tags: ["m4a1s", "decimator"],
    stickers: [{ name: "Winged Defuser", wear: 28, position: 1 }],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/m4a1s-decimator-mw",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/M4A1-S%20%7C%20Decimator%20%28Minimal%20Wear%29",
      marketCSGO: "https://market.csgo.com/item/m4a1s-decimator-mw",
    },
    accountId: "3",
  },
  {
    id: "38",
    itemName: "StatTrak™ Desert Eagle | Sunset Storm 壱 (Factory New)",
    buyPrice: 325.0,
    buyDate: "2023-10-12",
    market: "Market.CSGO",
    assetId: "MC_666777999",
    status: "sold",
    sellPrice: 285.5,
    sellDate: "2024-01-05",
    sellMarket: "Steam Market",
    profit: -39.5,
    profitPercentage: -12.15,
    potentialProfit: 0,
    tags: ["stattrak", "deagle", "sunset-storm"],
    stickers: [
      { name: "Kawaii Killer CT", wear: 15, position: 1 },
      { name: "Kawaii Killer Terrorist", wear: 18, position: 2 },
    ],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/deagle-sunset-storm-fn-st",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/StatTrak%E2%84%A2%20Desert%20Eagle%20%7C%20Sunset%20Storm%20%E5%A3%B1%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/deagle-sunset-storm-fn-st",
    },
    accountId: "4",
  },
  {
    id: "39",
    itemName: "P90 | Death by Kitty (Minimal Wear)",
    buyPrice: 85.0,
    buyDate: "2024-01-18",
    market: "Steam Market",
    assetId: "SM_777999888",
    status: "ready_to_trade",
    sellPrice: null,
    sellDate: null,
    delivered_to_steam: true,
    targetSellMarket: "Market.CSGO",
    currentMarketPrice: 92.25,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 7.25,
    tags: ["p90", "death-by-kitty"],
    stickers: [{ name: "Kawaii Killer CT", wear: 25, position: 1 }],
    charm: { name: "Backstab" },
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/p90-death-by-kitty-mw",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/P90%20%7C%20Death%20by%20Kitty%20%28Minimal%20Wear%29",
      marketCSGO: "https://market.csgo.com/item/p90-death-by-kitty-mw",
    },
    accountId: "5",
  },
  {
    id: "40",
    itemName: "★ Falchion Knife | Fade (Factory New)",
    buyPrice: 485.0,
    buyDate: "2023-12-01",
    market: "Lis-Skins",
    assetId: "LS_888999777",
    status: "sold",
    sellPrice: 525.75,
    sellDate: "2024-02-10",
    sellMarket: "Market.CSGO",
    profit: 40.75,
    profitPercentage: 8.4,
    potentialProfit: 0,
    tags: ["knife", "falchion", "fade"],
    stickers: [],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/falchion-knife-fade-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/%E2%98%85%20Falchion%20Knife%20%7C%20Fade%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/falchion-knife-fade-fn",
    },
    accountId: "6",
  },
  {
    id: "41",
    itemName: "AK-47 | Wasteland Rebel (Field-Tested)",
    buyPrice: 58.5,
    buyDate: "2024-02-01",
    market: "Market.CSGO",
    assetId: "MC_111333777",
    status: "unsold",
    sellPrice: null,
    sellDate: null,
    targetSellMarket: "Lis-Skins",
    currentMarketPrice: 65.25,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 6.75,
    tags: ["ak47", "wasteland-rebel"],
    stickers: [
      { name: "Fnatic | Katowice 2015", wear: 32, position: 1 },
      { name: "TSM | Katowice 2015", wear: 28, position: 2 },
    ],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/ak47-wasteland-rebel-ft",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Wasteland%20Rebel%20%28Field-Tested%29",
      marketCSGO: "https://market.csgo.com/item/ak47-wasteland-rebel-ft",
    },
    accountId: "1",
  },
  {
    id: "42",
    itemName: "Souvenir AWP | Pink DDPAT (Field-Tested)",
    buyPrice: 385.0,
    buyDate: "2023-09-25",
    market: "Steam Market",
    assetId: "SM_222444888",
    status: "sold",
    sellPrice: 465.75,
    sellDate: "2023-12-20",
    sellMarket: "Lis-Skins",
    profit: 80.75,
    profitPercentage: 20.97,
    potentialProfit: 0,
    tags: ["souvenir", "awp", "pink-ddpat"],
    stickers: [
      { name: "Gold ESL Wolf (Foil)", wear: 5, position: 1 },
      { name: "Virtus.pro (Gold) | Katowice 2014", wear: 8, position: 2 },
    ],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/awp-pink-ddpat-ft-souvenir",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/Souvenir%20AWP%20%7C%20Pink%20DDPAT%20%28Field-Tested%29",
      marketCSGO: "https://market.csgo.com/item/awp-pink-ddpat-ft-souvenir",
    },
    accountId: "2",
  },
  {
    id: "43",
    itemName: "Glock-18 | Water Elemental (Minimal Wear)",
    buyPrice: 18.5,
    buyDate: "2024-02-07",
    market: "Lis-Skins",
    assetId: "LS_333555999",
    status: "trade_ban",
    sellPrice: null,
    sellDate: null,
    delivered_to_steam: true,
    trade_ban_until: "2024-02-14T12:30:00Z",
    targetSellMarket: "Market.CSGO",
    currentMarketPrice: 22.75,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 4.25,
    tags: ["glock", "water-elemental"],
    stickers: [{ name: "Splash", wear: 40, position: 1 }],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/glock-18-water-elemental-mw",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/Glock-18%20%7C%20Water%20Elemental%20%28Minimal%20Wear%29",
      marketCSGO: "https://market.csgo.com/item/glock-18-water-elemental-mw",
    },
    accountId: "3",
  },
  {
    id: "44",
    itemName: "★ Stiletto Knife | Vanilla",
    buyPrice: 275.0,
    buyDate: "2024-01-08",
    market: "Market.CSGO",
    assetId: "MC_444666999",
    status: "unsold",
    sellPrice: null,
    sellDate: null,
    targetSellMarket: "Steam Market",
    currentMarketPrice: 285.5,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 10.5,
    tags: ["knife", "stiletto", "vanilla"],
    stickers: [],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/stiletto-knife-vanilla",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/%E2%98%85%20Stiletto%20Knife",
      marketCSGO: "https://market.csgo.com/item/stiletto-knife-vanilla",
    },
    accountId: "4",
  },
  {
    id: "45",
    itemName: "M4A4 | The Emperor (Field-Tested)",
    buyPrice: 185.0,
    buyDate: "2023-11-15",
    market: "Steam Market",
    assetId: "SM_555777111",
    status: "sold",
    sellPrice: 165.25,
    sellDate: "2024-01-12",
    sellMarket: "Market.CSGO",
    profit: -19.75,
    profitPercentage: -10.68,
    potentialProfit: 0,
    tags: ["m4a4", "emperor"],
    stickers: [
      { name: "Natus Vincere | MLG Columbus 2016", wear: 22, position: 1 },
      { name: "Luminosity Gaming | MLG Columbus 2016", wear: 25, position: 2 },
    ],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/m4a4-emperor-ft",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/M4A4%20%7C%20The%20Emperor%20%28Field-Tested%29",
      marketCSGO: "https://market.csgo.com/item/m4a4-emperor-ft",
    },
    accountId: "5",
  },
  {
    id: "46",
    itemName: "StatTrak™ SSG 08 | Blood in the Water (Minimal Wear)",
    buyPrice: 485.0,
    buyDate: "2023-10-30",
    market: "Lis-Skins",
    assetId: "LS_666888222",
    status: "sold",
    sellPrice: 545.75,
    sellDate: "2024-01-25",
    sellMarket: "Steam Market",
    profit: 60.75,
    profitPercentage: 12.53,
    potentialProfit: 0,
    tags: ["stattrak", "ssg08", "blood-in-water"],
    stickers: [{ name: "Fearsome", wear: 12, position: 1 }],
    charm: { name: "Backstab" },
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/ssg08-blood-in-water-mw-st",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/StatTrak%E2%84%A2%20SSG%2008%20%7C%20Blood%20in%20the%20Water%20%28Minimal%20Wear%29",
      marketCSGO: "https://market.csgo.com/item/ssg08-blood-in-water-mw-st",
    },
    accountId: "6",
  },
  {
    id: "47",
    itemName: "AK-47 | Fuel Injector (Battle-Scarred)",
    buyPrice: 35.5,
    buyDate: "2024-02-09",
    market: "Market.CSGO",
    assetId: "MC_777111444",
    status: "waiting_unlock",
    sellPrice: null,
    sellDate: null,
    unlock_at: "2024-02-16T18:45:00Z",
    delivered_to_steam: false,
    targetSellMarket: "Lis-Skins",
    currentMarketPrice: 39.75,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 4.25,
    tags: ["ak47", "fuel-injector"],
    stickers: [{ name: "Firestarter (Holo)", wear: 30, position: 1 }],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/ak47-fuel-injector-bs",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Fuel%20Injector%20%28Battle-Scarred%29",
      marketCSGO: "https://market.csgo.com/item/ak47-fuel-injector-bs",
    },
    accountId: "1",
  },
  {
    id: "48",
    itemName: "★ Ursus Knife | Slaughter (Factory New)",
    buyPrice: 685.0,
    buyDate: "2023-12-15",
    market: "Steam Market",
    assetId: "SM_888222555",
    status: "unsold",
    sellPrice: null,
    sellDate: null,
    targetSellMarket: "Lis-Skins",
    currentMarketPrice: 725.5,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 40.5,
    tags: ["knife", "ursus", "slaughter"],
    stickers: [],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/ursus-knife-slaughter-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/%E2%98%85%20Ursus%20Knife%20%7C%20Slaughter%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/ursus-knife-slaughter-fn",
    },
    accountId: "2",
  },
  {
    id: "49",
    itemName: "Nova | Toy Soldier (Factory New)",
    buyPrice: 8.25,
    buyDate: "2024-02-10",
    market: "Lis-Skins",
    assetId: "LS_999333666",
    status: "unsold",
    sellPrice: null,
    sellDate: null,
    targetSellMarket: "Market.CSGO",
    currentMarketPrice: 12.5,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 4.25,
    tags: ["nova", "toy-soldier"],
    stickers: [
      { name: "Welcome to the Clutch", wear: 15, position: 1 },
      { name: "Good Luck", wear: 18, position: 2 },
    ],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/nova-toy-soldier-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/Nova%20%7C%20Toy%20Soldier%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/nova-toy-soldier-fn",
    },
    accountId: "3",
  },
  {
    id: "50",
    itemName: "★ Shadow Daggers | Doppler (Factory New)",
    buyPrice: 395.0,
    buyDate: "2024-01-25",
    market: "Market.CSGO",
    assetId: "MC_111555888",
    status: "ready_to_trade",
    sellPrice: null,
    sellDate: null,
    delivered_to_steam: true,
    targetSellMarket: "Steam Market",
    currentMarketPrice: 425.75,
    profit: 0,
    profitPercentage: 0,
    potentialProfit: 30.75,
    tags: ["knife", "shadow-daggers", "doppler"],
    stickers: [],
    marketLinks: {
      lisSkins: "https://lis-skins.ru/item/shadow-daggers-doppler-fn",
      steamMarket:
        "https://steamcommunity.com/market/listings/730/%E2%98%85%20Shadow%20Daggers%20%7C%20Doppler%20%28Factory%20New%29",
      marketCSGO: "https://market.csgo.com/item/shadow-daggers-doppler-fn",
    },
    accountId: "4",
  },
];

export const calculateStats = (items: TradingItem[]): TradingStats => {
  const totalSpent = items.reduce((sum, item) => sum + item.buyPrice, 0);
  const totalEarned = items
    .filter((item) => item.status === "sold")
    .reduce((sum, item) => sum + (item.sellPrice || 0), 0);
  const totalProfit = items.reduce((sum, item) => sum + item.profit, 0);
  const soldItems = items.filter((item) => item.status === "sold");
  const averageROI =
    soldItems.length > 0
      ? soldItems.reduce((sum, item) => sum + item.profitPercentage, 0) /
        soldItems.length
      : 0;
  const itemsInInventory = items.filter(
    (item) =>
      item.status === "unsold" ||
      item.status === "waiting_unlock" ||
      item.status === "trade_ban" ||
      item.status === "ready_to_trade",
  ).length;

  return {
    totalSpent,
    totalEarned,
    totalProfit,
    averageROI,
    itemsInInventory,
    totalItems: items.length,
  };
};

export const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount);
};

export const formatPercentage = (percentage: number): string => {
  return `${percentage >= 0 ? "+" : ""}${percentage.toFixed(2)}%`;
};

export const formatDate = (dateString: string): string => {
  return new Date(dateString).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
};
